[package]
name = "blog-code-samples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
ring = "0.17.6"
fluent-hash = "0.2.3"
primes = "0.3.0"